# Generated by Django 3.2.dev20200924115306 on 2021-02-15 08:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MECU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'ECU',
            },
        ),
        migrations.CreateModel(
            name='MProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='MType_input',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'Type_input',
            },
        ),
        migrations.CreateModel(
            name='MVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpm_web.mproject')),
            ],
            options={
                'db_table': 'Version',
            },
        ),
        migrations.CreateModel(
            name='MRelease_input',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.CharField(blank=True, default=datetime.datetime.today, max_length=50)),
                ('plan', models.CharField(blank=True, default='', max_length=50)),
                ('flag_visual', models.BooleanField(blank=True, default=True)),
                ('dx_ecu', models.CharField(blank=True, default='', max_length=50)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('id_ecu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpm_web.mecu')),
                ('id_type_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpm_web.mtype_input')),
            ],
            options={
                'db_table': 'Release_input',
            },
        ),
        migrations.AddField(
            model_name='mecu',
            name='id_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpm_web.mversion'),
        ),
    ]
