# Generated by Django 3.2.dev20200924115306 on 2021-02-23 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0002_auto_20210215_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='mversion',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime.today, max_length=50),
        ),
    ]
