# Generated by Django 3.2.dev20200924115306 on 2021-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0003_mversion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecu',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
