# Generated by Django 3.2.dev20200924115306 on 2021-03-04 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0004_alter_mecu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproject',
            name='date_end',
            field=models.CharField(blank=True, default=datetime.datetime.today, max_length=50),
        ),
        migrations.AddField(
            model_name='mproject',
            name='date_ini',
            field=models.CharField(blank=True, default=datetime.datetime.today, max_length=50),
        ),
        migrations.AddField(
            model_name='mproject',
            name='date_status',
            field=models.CharField(blank=True, default=datetime.datetime.today, max_length=50),
        ),
        migrations.AddField(
            model_name='mproject',
            name='factor_weeks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='mproject',
            name='max_ecu_slide',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
