# Generated by Django 3.2.dev20200924115306 on 2021-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0005_auto_20210304_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrelease_input',
            name='dx_ecu',
        ),
        migrations.AddField(
            model_name='mecu',
            name='dx_ecu',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
