# Generated by Django 3.2.dev20200924115306 on 2021-03-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0008_remove_mrelease_input_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrelease_input',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
