# Generated by Django 3.2.dev20200924115306 on 2021-03-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0013_delete_mplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'Plan',
            },
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpm_web.mplan'),
        ),
    ]
