# Generated by Django 3.2.dev20200924115306 on 2021-03-05 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0019_auto_20210305_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproject',
            name='factor_weeks',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='max_ecu_slide',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
