# Generated by Django 3.2.dev20200924115306 on 2021-03-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0020_auto_20210305_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproject',
            name='date_end',
            field=models.CharField(blank=True, default='08032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_ini',
            field=models.CharField(blank=True, default='08Y032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_status',
            field=models.CharField(blank=True, default='08032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_beantragt',
            field=models.CharField(blank=True, default='08032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='id_ecu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpm_web.mecu'),
        ),
    ]
