# Generated by Django 3.2.dev20200924115306 on 2021-03-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0021_auto_20210308_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrelease_input',
            name='flag_marked1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='mrelease_input',
            name='flag_marked2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='mrelease_input',
            name='flag_marked3',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
