# Generated by Django 3.2.dev20200924115306 on 2021-03-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpm_web', '0022_auto_20210308_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproject',
            name='date_end',
            field=models.CharField(blank=True, default='09032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_ini',
            field=models.CharField(blank=True, default='09Y032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_status',
            field=models.CharField(blank=True, default='09032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_beantragt',
            field=models.CharField(blank=True, default='09032021', max_length=50),
        ),
        migrations.CreateModel(
            name='MConfig_prj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marked1_color', models.CharField(blank=True, default='', max_length=10)),
                ('marked1_w', models.CharField(blank=True, default='', max_length=10)),
                ('marked2_color', models.CharField(blank=True, default='', max_length=10)),
                ('marked2_w', models.CharField(blank=True, default='', max_length=10)),
                ('marked3_color', models.CharField(blank=True, default='', max_length=10)),
                ('marked3_w', models.CharField(blank=True, default='', max_length=10)),
                ('week_color', models.CharField(blank=True, default='', max_length=10)),
                ('week_w', models.CharField(blank=True, default='', max_length=10)),
                ('flag_head', models.BooleanField(blank=True, default=False)),
                ('flag_footer', models.BooleanField(blank=True, default=False)),
                ('flag_title', models.BooleanField(blank=True, default=False)),
                ('flag_legend', models.BooleanField(blank=True, default=False)),
                ('flag_logo', models.BooleanField(blank=True, default=False)),
                ('flag_status_date', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('fig1_color_1', models.CharField(blank=True, default='', max_length=10)),
                ('fig1_color_2', models.CharField(blank=True, default='', max_length=10)),
                ('fig1_color_3', models.CharField(blank=True, default='', max_length=10)),
                ('fig1_w', models.CharField(blank=True, default='', max_length=10)),
                ('fig1_border_w', models.CharField(blank=True, default='', max_length=10)),
                ('fig1_name', models.CharField(blank=True, default='', max_length=50)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Config_prj',
            },
        ),
    ]
