# Generated by Django 3.2.dev20200924115306 on 2021-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0023_auto_20210309_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mconfig_prj',
            name='fig1_border_w',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='fig1_w',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='flag_footer',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='flag_head',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='flag_legend',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='flag_logo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='flag_status_date',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='flag_title',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='marked1_color',
            field=models.CharField(blank=True, default='dc143c', max_length=10),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='marked1_w',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='marked2_w',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='marked3_w',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='week_w',
            field=models.IntegerField(default=1),
        ),
    ]
