# Generated by Django 3.2.dev20200924115306 on 2021-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0025_auto_20210309_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mconfig_prj',
            name='marked1_color',
            field=models.CharField(blank=True, default='#dc143c', max_length=10),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='marked2_color',
            field=models.CharField(blank=True, default='#5feb4c', max_length=10),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='marked3_color',
            field=models.CharField(blank=True, default='#eb4cc2', max_length=10),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='week_color',
            field=models.CharField(blank=True, default='#bbe0e3', max_length=10),
        ),
    ]
