# Generated by Django 3.2.dev20200924115306 on 2021-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0026_auto_20210309_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mconfig_prj',
            name='week_w',
        ),
        migrations.AddField(
            model_name='mconfig_prj',
            name='week_s',
            field=models.FloatField(default=0.28),
        ),
    ]
