# Generated by Django 3.2.dev20200924115306 on 2021-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0027_auto_20210309_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mconfig_prj',
            name='fig1_w',
        ),
        migrations.AddField(
            model_name='mconfig_prj',
            name='fig1_s',
            field=models.FloatField(default=0.28),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_end',
            field=models.CharField(blank=True, default='10032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_ini',
            field=models.CharField(blank=True, default='10Y032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_status',
            field=models.CharField(blank=True, default='10032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_beantragt',
            field=models.CharField(blank=True, default='10032021', max_length=50),
        ),
    ]
