# Generated by Django 3.2.dev20200924115306 on 2021-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0028_auto_20210310_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='mconfig_prj',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mconfig_prj',
            name='type_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
