# Generated by Django 3.2.dev20200924115306 on 2021-03-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0029_auto_20210310_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mconfig_prj',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='mconfig_prj',
            name='type_name',
        ),
    ]
