# Generated by Django 3.2.dev20200924115306 on 2021-03-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0032_auto_20210315_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplan2',
            name='fig1_color_1',
            field=models.CharField(blank=True, default='#dc143c', max_length=10),
        ),
        migrations.AlterField(
            model_name='mplan2',
            name='fig1_color_2',
            field=models.CharField(blank=True, default='#dc143c', max_length=10),
        ),
        migrations.AlterField(
            model_name='mplan2',
            name='fig1_color_3',
            field=models.CharField(blank=True, default='#dc143c', max_length=10),
        ),
    ]
