# Generated by Django 3.2.dev20200924115306 on 2021-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0033_auto_20210315_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtype_input2',
            name='fig1_name',
            field=models.CharField(blank=True, default='pptx.ShapeType.ellipse', max_length=100),
        ),
    ]
