# Generated by Django 3.2.dev20200924115306 on 2021-03-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0034_alter_mtype_input2_fig1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplan2',
            name='fig1_border_w',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='mplan2',
            name='fig1_color_2',
            field=models.CharField(blank=True, default='#000000', max_length=10),
        ),
    ]
