# Generated by Django 3.2.dev20200924115306 on 2021-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0036_auto_20210315_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mconfig_prj',
            name='marked1_w',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_end',
            field=models.CharField(blank=True, default='16032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_ini',
            field=models.CharField(blank=True, default='16Y032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_status',
            field=models.CharField(blank=True, default='16032021', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_beantragt',
            field=models.CharField(blank=True, default='16032021', max_length=50),
        ),
    ]
