# Generated by Django 3.2.dev20200924115306 on 2021-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0037_auto_20210316_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mconfig_prj',
            name='created_by',
            field=models.CharField(blank=True, default='[EE-32]', max_length=200),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='logo_url',
            field=models.CharField(blank=True, default='/static/brand/logos_seat_cupra.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='mconfig_prj',
            name='title',
            field=models.CharField(blank=True, default='STATUS REPORT E/E', max_length=200),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_end',
            field=models.CharField(blank=True, default='2021-03-22', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_ini',
            field=models.CharField(blank=True, default='2021-03-22', max_length=50),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_status',
            field=models.CharField(blank=True, default='2021-03-22', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_beantragt',
            field=models.CharField(blank=True, default='22032021', max_length=50),
        ),
    ]
