# Generated by Django 3.2.dev20200924115306 on 2021-03-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0040_auto_20210324_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrelease_input',
            name='id_ecu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpm_web.mecu'),
        ),
    ]
