# Generated by Django 3.2.dev20200924115306 on 2021-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0042_auto_20210325_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproject',
            name='date_created',
            field=models.CharField(blank=True, default='25-03-2021 00:00', max_length=50),
        ),
    ]
