# Generated by Django 3.2.dev20200924115306 on 2021-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0047_auto_20210326_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='MUser_extra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flag_first_time', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'User_extra',
            },
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_created',
            field=models.CharField(blank=True, default='26/03/2021-09:46', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_created',
            field=models.CharField(blank=True, default='26/03/2021-09:46', max_length=50),
        ),
    ]
