# Generated by Django 3.2.dev20200924115306 on 2021-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0049_auto_20210326_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser_extra',
            name='flag_first_time_conf',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='muser_extra',
            name='flag_first_time_prj',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='muser_extra',
            name='flag_first_time_profile',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_created',
            field=models.CharField(blank=True, default='26/03/2021-11:33', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_created',
            field=models.CharField(blank=True, default='26/03/2021-11:33', max_length=50),
        ),
    ]
