# Generated by Django 3.2.dev20200924115306 on 2021-04-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0058_auto_20210420_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrelease_input',
            name='extra1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mrelease_input',
            name='extra2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mrelease_input',
            name='extra3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_created',
            field=models.CharField(blank=True, default='20/04/2021-10:19', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_created',
            field=models.CharField(blank=True, default='20/04/2021-10:19', max_length=50),
        ),
    ]
