# Generated by Django 3.2.dev20200924115306 on 2021-04-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0059_auto_20210420_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproject',
            name='date_created',
            field=models.CharField(blank=True, default='20/04/2021-12:41', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_created',
            field=models.CharField(blank=True, default='20/04/2021-12:41', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='n_version',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
