# Generated by Django 3.2.dev20200924115306 on 2021-04-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0061_auto_20210423_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser_extra',
            name='access_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_created',
            field=models.CharField(blank=True, default='23/04/2021-10:31', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_created',
            field=models.CharField(blank=True, default='23/04/2021-10:31', max_length=50),
        ),
    ]
