# Generated by Django 3.2.dev20200924115306 on 2021-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm_web', '0063_auto_20210423_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplan2',
            name='access_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mtype_input2',
            name='access_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mproject',
            name='date_created',
            field=models.CharField(blank=True, default='23/04/2021-16:17', max_length=50),
        ),
        migrations.AlterField(
            model_name='mrelease_input',
            name='date_created',
            field=models.CharField(blank=True, default='23/04/2021-16:17', max_length=50),
        ),
    ]
